name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - flask=2.0.3
  - werkzeug=2.0.3
  - pip
  - pip:
      - python-docx==0.8.11
      - PyPDF2==3.0.1
      - nltk==3.6.7
      - PyMuPDF==1.25.2
